stages:
  - validate

shellcheck:
  image: koalaman/shellcheck-alpine:latest
  stage: validate
  before_script:
  - apk update
  - apk add git
  script:
  - git ls-files --exclude='*.sh' --ignored --cached | xargs shellcheck

