stages:
  - validate

shellcheck:
  image: koalaman/shellcheck-alpine:latest
  stage: validate
  before_script:
  - apk update
  - apk add git
  script:
  - git ls-files --exclude='*.sh' --ignored --cached | xargs shellcheck

vint:
  image: renovate/pip
  stage: validate
  before_script:
  - pip install vim-vint --user
  script:
  - git ls-files --exclude='*.vim' --ignored --cached | xargs /home/ubuntu/.local/bin/vint -V

