stages:
  - test

test:
    image: koalaman/shellcheck-alpine:latest
    stage: test
    before_script:
    - apk update
    - apk add git
    script:
    - git ls-files --exclude='*.sh' --ignored | xargs shellcheck
