stages:
  - validate

shellcheck:
  image: koalaman/shellcheck-alpine:latest
  stage: validate
  before_script:
  - apk update
  - apk add git
  script:
  - git ls-files --exclude='*.sh' --ignored | xargs shellcheck

vint:
  image: renovate/pip
  stage: validate
  before_script:
  - pip install vint
  script:
  - git ls-files --exclude='*.vim' --ignored | xargs vint

image_check:
  image: python:latest
  stage: validate
  script:
  - pip install vint --user
  - xargs --version
  - vint --version

