# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
palette = "catppuccin_mocha"

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$python\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

add_newline = true

# the prompt character
[character]
success_symbol = "[⟩](green)"
vimcmd_symbol = "[⟨](green)"
error_symbol = "[❯](bold red)"

# battery config for laptop
[[battery.display]]
threshold = 30
style = 'bold red'

# show how long a command took to execute
[cmd_duration]
min_time = 10_000
format = "[⏱ $duration](yellow)"
show_notifications = false
min_time_to_notify = 60_000

# shows current direcory
[directory]
truncation_length = 5
truncate_to_repo = true
truncation_symbol = "…/"
style = "cyan"

# maybe set up to show amount of commits ahead/behind master/origin
[git_branch]
format = "[ $symbol$branch ]($style)"

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"
format = '([$added]($added_style))[±](peach)([$deleted]($deleted_style) )'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold red"

[hg_branch]
format = "[ $branch](bold purle)"

[java]
format = "[ ${symbol}${version}]($style)"




[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
